### ISSUE TITLE
Using a chart from CC as a sub-chart dependency

### ISSUE THREAD

**Issue by longwa** [jfrog/chartcenter#20]
When using chartcenter, the charts have an extra path element that is the original repo. This works fine for installation and fetching, but how do you use them as subcharts?
```
dependencies:
  - name: bitnami/rabbitmq
    version: 7.5.8
    repository: https://repo.chartcenter.io
```
When I try to use the above in a chart, I can run `helm dependency update` and it pulls down a file called `rabbitmq-7.5.8.tgz` but when you try to use the chart you get:

```
Error: found in Chart.yaml, but missing in charts/ directory: bitnami/rabbitmq
```
I'm assuming this is because of the extra path element. Is there some trick to make this work?
